### ISSUE TITLE
Overflowed by x pixels in bottom carousel

### ISSUE THREAD

**Issue by JotaFerreira** [SnakeyHips/recipeapp#1]
Device: Asus 2 laser - 5.5 inches

![image](https://user-images.githubusercontent.com/13682634/50302748-2b416680-0472-11e9-9f8f-36180540581e.png)

**Comment by soupjake** [comment]
Whoops! Will fix this tomorrow 😅

**Comment by soupjake** [comment]
Okay updated `home_page.dart` to hopefully fix this. Can you give it a go and let me know if it's solved the issue?

**Comment by JotaFerreira** [comment]
nice! Works fine now. Thanks!
